- name: bug
  color: d73a4a
  description: Something isn't working

- name: enhancement
  color: a2eeef
  description: New feature or request

- name: good first issue
  color: 7057ff
  description: Good for newcomers

- name: help wanted
  color: 008672
  description: Extra attention is needed

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists

- name: invalid
  color: e4e669
  description: This doesn't seem right

- name: wontfix
  color: ffffff
  description: This will not be worked on

- name: new tool
  color: 1d76db
  description: Adding a new tool

- name: ui/ux
  color: d876e3
  description: User interface or experience improvements

- name: performance
  color: fbca04
  description: Performance improvements

- name: security
  color: ee0701
  description: Security related issues
