import { Metadata } from 'next';
import { generatePageMetadata, ToolMetadata } from './metadata';

export interface ToolInfo extends ToolMetadata {
  category: string;
  priority: number;
  changeFrequency: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
  features: string[];
  useCases: string[];
  relatedTools: string[];
}

export const toolsData: Record<string, ToolInfo> = {
  'json-to-typescript': {
    title: 'JSON to TypeScript Converter - Generate TypeScript Interfaces & Types Instantly',
    description: 'Convert JSON to TypeScript interfaces and types instantly with our powerful converter. Features intelligent type inference, supports multiple JSON samples, generates nested interfaces, and creates mock data. 100% free, client-side processing - your data never leaves your browser. Perfect for API integration and type-safe development.',
    path: '/json-to-typescript',
    keywords: [
      'json to typescript converter',
      'typescript interface generator',
      'json to ts',
      'typescript types from json',
      'automatic type inference',
      'generate typescript interfaces',
      'json to typescript online',
      'typescript type generator',
      'json parser to typescript',
      'typescript interface from json object',
      'convert json response to typescript',
      'api typescript types generator',
      'json schema typescript',
      'typescript model generator',
      'json to typescript class',
      'json to interface typescript',
      'generate types from api response',
      'typescript code generation',
      'json type inference',
      'best json to typescript converter',
    ],
    ogTitle: 'Best JSON to TypeScript Converter - Generate Types Instantly',
    ogDescription: 'Transform JSON to TypeScript interfaces instantly. Smart type inference, multi-sample support, 100% client-side & free.',
    category: 'JSON Tools',
    priority: 1.0,
    changeFrequency: 'weekly',
    features: ['Type inference', 'Multi-sample support', 'Nested interfaces', 'Mock data generation', 'Interface naming'],
    useCases: ['API integration', 'Type-safe development', 'Frontend-backend sync', 'Documentation generation'],
    relatedTools: ['json-to-zod', 'json-to-json-schema', 'json-schema-to-typescript', 'typescript-to-zod'],
  },
  
  'json-to-zod': {
    title: 'JSON to Zod Schema Generator - Create Runtime Validation Schemas',
    description: 'Generate Zod validation schemas from JSON data automatically. Create runtime type-safe schemas with intelligent type inference, custom validations, and full TypeScript integration. Perfect for form validation, API validation, and data sanitization. Free, privacy-focused, works offline.',
    path: '/json-to-zod',
    keywords: [
      'json to zod',
      'zod schema generator',
      'zod validation schema',
      'runtime validation',
      'type-safe validation',
      'zod from json',
      'generate zod schema',
      'zod typescript validation',
      'json to zod online',
      'zod schema creator',
      'automatic zod generation',
      'zod validator generator',
      'form validation zod',
      'api validation zod',
      'zod schema from api',
      'typescript zod converter',
      'zod type inference',
      'json schema to zod',
      'zod object validation',
      'best zod generator',
    ],
    ogTitle: 'JSON to Zod Schema Generator - Runtime Type Validation',
    ogDescription: 'Generate Zod schemas from JSON instantly. Runtime validation with TypeScript integration. Free & client-side.',
    category: 'Validation Tools',
    priority: 0.95,
    changeFrequency: 'weekly',
    features: ['Type inference', 'Custom validations', 'Nested schemas', 'Enum support', 'Optional fields'],
    useCases: ['Form validation', 'API validation', 'Data sanitization', 'Runtime type checking'],
    relatedTools: ['json-to-typescript', 'validator', 'typescript-to-zod', 'zod-to-typescript'],
  },
  
  'json-formatter': {
    title: 'JSON Formatter & Validator - Beautify, Prettify & Minify JSON Online',
    description: 'Format, validate, beautify, and minify JSON with our professional online formatter. Features syntax highlighting, real-time error detection, JSON sorting, and tree view. Handles large JSON files with ease. No data sent to servers - 100% client-side processing. Free developer tool.',
    path: '/json-formatter',
    keywords: [
      'json formatter',
      'json beautifier',
      'json validator',
      'json minifier',
      'prettify json',
      'format json online',
      'json pretty print',
      'json lint',
      'json parser online',
      'validate json online',
      'json syntax highlighter',
      'json tree viewer',
      'json editor online',
      'json string formatter',
      'compress json',
      'json unminify',
      'online json tool',
      'json checker',
      'json validation tool',
      'best json formatter',
    ],
    ogTitle: 'JSON Formatter & Validator - Free Online Tool',
    ogDescription: 'Format, validate & beautify JSON instantly. Syntax highlighting, error detection, 100% client-side. Try now!',
    category: 'JSON Tools',
    priority: 0.9,
    changeFrequency: 'monthly',
    features: ['Syntax highlighting', 'Error detection', 'Sort keys', 'Minify/Beautify', 'Tree view'],
    useCases: ['Debugging APIs', 'Config file editing', 'Data visualization', 'JSON editing'],
    relatedTools: ['json-to-typescript', 'json-to-zod', 'json-diff', 'validator'],
  },
  
  'regex-tester': {
    title: 'RegEx Tester & Debugger - Test Regular Expressions Online Free',
    description: 'Test, debug, and build regular expressions with live match highlighting. Supports all JavaScript regex flags (g, i, m, s, u, y), capture groups, and replacements. Perfect for pattern matching, data validation, and string manipulation. Free online regex tester with instant results.',
    path: '/regex-tester',
    keywords: [
      'regex tester',
      'regular expression tester',
      'regex validator',
      'regex match online',
      'regex debugger',
      'test regular expressions',
      'regex online tool',
      'regex builder',
      'javascript regex tester',
      'regex pattern matcher',
      'regex flags tester',
      'regex capture groups',
      'regex replace online',
      'regex cheat sheet',
      'regex playground',
      'online regex editor',
      'regex validator tool',
      'regular expression debugger',
      'test regex patterns',
      'best regex tester',
    ],
    ogTitle: 'RegEx Tester - Test Regular Expressions Online',
    ogDescription: 'Test & debug regex patterns instantly. Live matching, all flags supported, capture groups. Free tool!',
    category: 'Developer Tools',
    priority: 0.9,
    changeFrequency: 'monthly',
    features: ['Live matching', 'All flags support', 'Capture groups', 'Replace mode', 'Pattern explanation'],
    useCases: ['Form validation', 'Data parsing', 'Search & replace', 'Pattern extraction'],
    relatedTools: ['validator', 'url-encoder', 'base64'],
  },
  
  'base64': {
    title: 'Base64 Encoder & Decoder - Convert Base64 Online Free',
    description: 'Encode and decode Base64 strings instantly with our secure online converter. Supports text, files, and URLs. Bidirectional conversion with copy-to-clipboard functionality. 100% client-side processing ensures your data stays private. Free Base64 encoder/decoder tool.',
    path: '/base64',
    keywords: [
      'base64 encoder',
      'base64 decoder',
      'base64 converter',
      'encode base64',
      'decode base64',
      'base64 online tool',
      'base64 text encoder',
      'base64 file encoder',
      'base64 url encoder',
      'base64 decode online',
      'base64 to text',
      'text to base64',
      'base64 encoder decoder',
      'base64 string converter',
      'javascript base64',
      'atob btoa online',
      'base64 encryption',
      'base64 data uri',
      'base64 image encoder',
      'best base64 tool',
    ],
    ogTitle: 'Base64 Encoder & Decoder - Free Online Tool',
    ogDescription: 'Encode & decode Base64 instantly. Text, files, URLs supported. 100% client-side, secure & free.',
    category: 'Encoding Tools',
    priority: 0.85,
    changeFrequency: 'monthly',
    features: ['Text encoding', 'File support', 'URL safe', 'Copy to clipboard', 'History'],
    useCases: ['Data transmission', 'URL parameters', 'Image embedding', 'API authentication'],
    relatedTools: ['url-encoder', 'jwt-decoder', 'hash-generator'],
  },
  
  'color-converter': {
    title: 'Color Converter - HEX to RGB, RGB to HSL, Color Picker Tool',
    description: 'Convert colors between HEX, RGB, HSL, RGBA, and HSLA formats instantly. Features visual color picker, color palette generation, contrast checker, and CSS output. Perfect for web designers and developers. Free online color converter with instant previews.',
    path: '/color-converter',
    keywords: [
      'color converter',
      'hex to rgb',
      'rgb to hex',
      'rgb to hsl',
      'hsl converter',
      'color picker online',
      'hex color converter',
      'rgb color code',
      'hsl color picker',
      'color code translator',
      'css color converter',
      'rgba converter',
      'hex to rgba',
      'color palette generator',
      'contrast checker',
      'web color tool',
      'designer color tool',
      'color format converter',
      'hexadecimal converter',
      'best color converter',
    ],
    ogTitle: 'Color Converter - HEX, RGB, HSL Converter with Picker',
    ogDescription: 'Convert colors between HEX, RGB, HSL instantly. Color picker, palette generator, CSS output. Free!',
    category: 'Design Tools',
    priority: 0.85,
    changeFrequency: 'monthly',
    features: ['Visual picker', 'Multi-format support', 'Palette generation', 'Contrast checker', 'CSS output'],
    useCases: ['Web design', 'CSS styling', 'Brand colors', 'Accessibility testing'],
    relatedTools: ['qr-generator', 'image-compressor', 'ascii-art'],
  },
  
  'qr-generator': {
    title: 'QR Code Generator - Create QR Codes Online Free',
    description: 'Generate QR codes from any text, URL, contact info, or WiFi credentials. Features custom colors, error correction levels, multiple formats (PNG, SVG), and instant download. Works offline, no tracking, 100% free. Perfect for marketing, business cards, and digital payments.',
    path: '/qr-generator',
    keywords: [
      'qr code generator',
      'qr generator free',
      'create qr code online',
      'qr code maker',
      'free qr code',
      'generate qr code',
      'qr code creator',
      'url to qr code',
      'text to qr code',
      'wifi qr code generator',
      'vcard qr code',
      'custom qr code',
      'qr code designer',
      'bulk qr generator',
      'dynamic qr code',
      'static qr code',
      'qr code png',
      'qr code svg',
      'marketing qr codes',
      'best qr generator',
    ],
    ogTitle: 'QR Code Generator - Create QR Codes Free Online',
    ogDescription: 'Generate QR codes for URLs, text, WiFi & more. Custom colors, instant download. Free & offline!',
    category: 'Utility Tools',
    priority: 0.85,
    changeFrequency: 'monthly',
    features: ['Custom colors', 'Error correction', 'Multiple formats', 'WiFi/Contact support', 'Instant download'],
    useCases: ['Marketing materials', 'Business cards', 'Digital payments', 'Product labeling'],
    relatedTools: ['color-converter', 'url-encoder', 'base64'],
  },
  
  'uuid-generator': {
    title: 'UUID Generator - Generate UUIDs v1, v4, v5, v7 Online',
    description: 'Generate UUIDs and GUIDs instantly with support for multiple versions (v1, v4, v5, v7). Features bulk generation, custom namespace support, and cryptographically secure random generation. Free online UUID generator for developers and system architects.',
    path: '/uuid-generator',
    keywords: [
      'uuid generator',
      'guid generator',
      'uuid v4 generator',
      'uuid v1',
      'uuid v7',
      'generate uuid online',
      'bulk uuid generator',
      'random uuid generator',
      'unique id generator',
      'guid creator',
      'uuid javascript',
      'uuid npm',
      'uuid library',
      'universal unique identifier',
      'globally unique identifier',
      'uuid format',
      'uuid validator',
      'custom uuid',
      'namespace uuid',
      'best uuid generator',
    ],
    ogTitle: 'UUID Generator - Generate UUIDs v1, v4, v5, v7 Online',
    ogDescription: 'Generate UUIDs & GUIDs instantly. Multiple versions, bulk generation, secure random. Free tool!',
    category: 'Developer Tools',
    priority: 0.85,
    changeFrequency: 'monthly',
    features: ['Multiple versions', 'Bulk generation', 'Secure random', 'Custom namespace', 'Copy all'],
    useCases: ['Database IDs', 'API keys', 'Session tokens', 'Distributed systems'],
    relatedTools: ['hash-generator', 'jwt-decoder', 'timestamp-converter'],
  },
  
  'hash-generator': {
    title: 'Hash Generator - MD5, SHA-1, SHA-256, SHA-512, SHA-3 Online',
    description: 'Generate cryptographic hashes (MD5, SHA-1, SHA-256, SHA-512, SHA-3, BLAKE) from any text or file. Features multiple algorithms, file hashing, HMAC support, and copy functionality. 100% client-side for maximum security. Free hash generator for developers.',
    path: '/hash-generator',
    keywords: [
      'hash generator',
      'md5 generator',
      'sha256 generator',
      'sha512 generator',
      'sha1 hash',
      'cryptographic hash',
      'file hash generator',
      'text hash online',
      'checksum generator',
      'md5 checksum',
      'sha checksum',
      'hmac generator',
      'hash calculator',
      'message digest',
      'secure hash algorithm',
      'blake hash',
      'password hash',
      'data integrity',
      'file verification',
      'best hash generator',
    ],
    ogTitle: 'Hash Generator - MD5, SHA-256, SHA-512 Online',
    ogDescription: 'Generate MD5, SHA-1, SHA-256, SHA-512 hashes instantly. File support, HMAC, 100% client-side. Free!',
    category: 'Security Tools',
    priority: 0.8,
    changeFrequency: 'monthly',
    features: ['Multiple algorithms', 'File hashing', 'HMAC support', 'Copy to clipboard', 'Lower/Upper case'],
    useCases: ['Password hashing', 'File verification', 'Data integrity', 'API signatures'],
    relatedTools: ['base64', 'jwt-decoder', 'uuid-generator'],
  },
  
  'jwt-decoder': {
    title: 'JWT Decoder - Decode & Inspect JSON Web Tokens Online',
    description: 'Decode and inspect JWT tokens instantly to view header, payload, and signature. Features token validation, expiration checking, Base64 decoding, and signature verification guidance. Supports RS256, HS256, and other algorithms. 100% client-side, secure, and free.',
    path: '/jwt-decoder',
    keywords: [
      'jwt decoder',
      'jwt parser',
      'decode jwt online',
      'json web token decoder',
      'jwt inspector',
      'jwt token viewer',
      'jwt debugger',
      'jwt validator',
      'jwt signature checker',
      'base64 jwt decoder',
      'jwt payload viewer',
      'jwt header decoder',
      'jwt expiration check',
      'access token decoder',
      'id token decoder',
      'jwt token breakdown',
      'jwt online tool',
      'jwt analyzer',
      'jwt verification tool',
      'best jwt decoder',
    ],
    ogTitle: 'JWT Decoder - Decode JSON Web Tokens Online',
    ogDescription: 'Decode JWT tokens instantly. View header, payload & signature. Token validation, 100% client-side. Free!',
    category: 'Developer Tools',
    priority: 0.85,
    changeFrequency: 'monthly',
    features: ['Header decode', 'Payload decode', 'Signature display', 'Expiration check', 'Algorithm info'],
    useCases: ['API debugging', 'Token inspection', 'Security analysis', 'OAuth debugging'],
    relatedTools: ['base64', 'hash-generator', 'uuid-generator'],
  },
  
  'csv-to-json': {
    title: 'CSV to JSON Converter - Convert CSV to JSON Online Free',
    description: 'Convert CSV files to JSON format instantly with automatic header detection, data type inference, and nested object support. Features delimiter detection, encoding options, and bulk conversion. Handles large CSV files efficiently. 100% client-side, free, and privacy-focused.',
    path: '/csv-to-json',
    keywords: [
      'csv to json',
      'csv converter',
      'csv parser',
      'convert csv to json',
      'csv to json online',
      'csv file converter',
      'excel to json',
      'spreadsheet to json',
      'csv json transformer',
      'csv data converter',
      'delimiter detection',
      'csv header mapping',
      'bulk csv converter',
      'csv to json api',
      'tabular data converter',
      'csv json online tool',
      'comma separated values',
      'tsv to json',
      'csv to object',
      'best csv converter',
    ],
    ogTitle: 'CSV to JSON Converter - Convert CSV to JSON Online',
    ogDescription: 'Convert CSV to JSON instantly. Auto header detection, type inference, bulk support. Free & client-side!',
    category: 'Data Conversion',
    priority: 0.85,
    changeFrequency: 'monthly',
    features: ['Header detection', 'Type inference', 'Delimiter options', 'Nested objects', 'Bulk support'],
    useCases: ['Data migration', 'API data prep', 'Database import', 'Report generation'],
    relatedTools: ['xml-to-json', 'yaml-to-json', 'json-formatter', 'json-to-typescript'],
  },
  
  'xml-to-json': {
    title: 'XML to JSON Converter - Bidirectional XML JSON Converter',
    description: 'Convert between XML and JSON formats bidirectionally with intelligent attribute handling, namespace support, and CDATA preservation. Features syntax highlighting, error detection, and pretty printing. Perfect for API integration and legacy system migration. Free online converter.',
    path: '/xml-to-json',
    keywords: [
      'xml to json',
      'json to xml',
      'xml converter',
      'xml parser',
      'convert xml to json',
      'xml json transformer',
      'xml data converter',
      'xml attribute handler',
      'xml namespace converter',
      'bidirectional xml json',
      'xml formatter',
      'xml validator',
      'xml online tool',
      'xml to object',
      'soap to json',
      'rest xml converter',
      'xml api converter',
      'xml schema converter',
      'legacy xml migration',
      'best xml converter',
    ],
    ogTitle: 'XML to JSON Converter - Bidirectional Converter',
    ogDescription: 'Convert XML to JSON bidirectionally. Attribute handling, namespace support, CDATA preservation. Free!',
    category: 'Data Conversion',
    priority: 0.8,
    changeFrequency: 'monthly',
    features: ['Bidirectional', 'Attribute handling', 'Namespace support', 'CDATA preservation', 'Syntax highlight'],
    useCases: ['API integration', 'Legacy migration', 'Data transformation', 'SOAP services'],
    relatedTools: ['csv-to-json', 'yaml-to-json', 'json-formatter', 'json-to-typescript'],
  },
  
  'yaml-to-json': {
    title: 'YAML to JSON Converter - Convert YAML to JSON Online',
    description: 'Convert between YAML and JSON formats with anchor/alias resolution, multi-document support, and comment preservation. Features syntax highlighting, error detection, and formatting options. Perfect for Docker Compose, Kubernetes, and configuration files. Free online YAML converter.',
    path: '/yaml-to-json',
    keywords: [
      'yaml to json',
      'json to yaml',
      'yaml converter',
      'yaml parser',
      'convert yaml to json',
      'yaml json transformer',
      'yaml online tool',
      'yaml formatter',
      'yaml validator',
      'docker compose converter',
      'kubernetes yaml json',
      'yaml config converter',
      'yaml anchor alias',
      'multi document yaml',
      'yaml syntax checker',
      'yaml indentation',
      'yaml to object',
      'yaml vs json',
      'yaml configuration',
      'best yaml converter',
    ],
    ogTitle: 'YAML to JSON Converter - Bidirectional Converter',
    ogDescription: 'Convert YAML to JSON bidirectionally. Anchor/alias support, multi-document, Docker/K8s ready. Free!',
    category: 'Data Conversion',
    priority: 0.8,
    changeFrequency: 'monthly',
    features: ['Bidirectional', 'Anchor/alias support', 'Multi-document', 'Comment handling', 'Syntax highlight'],
    useCases: ['Docker Compose', 'Kubernetes', 'CI/CD configs', 'CloudFormation'],
    relatedTools: ['csv-to-json', 'xml-to-json', 'json-formatter', 'json-to-typescript'],
  },
  
  'markdown-to-html': {
    title: 'Markdown to HTML Converter - Convert MD to HTML Online Free',
    description: 'Convert Markdown to HTML instantly with full CommonMark support, syntax highlighting, and live preview. Features GFM tables, task lists, and code blocks. Perfect for documentation, blogs, and content management. 100% client-side, free online markdown converter.',
    path: '/markdown-to-html',
    keywords: [
      'markdown to html',
      'markdown converter',
      'md to html',
      'convert markdown',
      'markdown parser',
      'markdown to html online',
      'github markdown converter',
      'commonmark converter',
      'markdown preview',
      'markdown renderer',
      'markdown syntax',
      'markdown formatter',
      'markdown editor',
      'markdown compiler',
      'gfm converter',
      'markdown tables',
      'markdown code blocks',
      'markdown links',
      'markdown images',
      'best markdown converter',
    ],
    ogTitle: 'Markdown to HTML Converter - Convert MD to HTML Online',
    ogDescription: 'Convert Markdown to HTML instantly. CommonMark support, syntax highlighting, live preview. Free!',
    category: 'Data Conversion',
    priority: 0.85,
    changeFrequency: 'monthly',
    features: ['CommonMark support', 'Syntax highlighting', 'GFM tables', 'Code blocks', 'Live preview'],
    useCases: ['Documentation', 'Blog posts', 'README files', 'Content management'],
    relatedTools: ['html-to-markdown', 'csv-to-json', 'xml-to-json', 'ascii-art'],
  },
  
  'html-to-markdown': {
    title: 'HTML to Markdown Converter - Convert HTML to MD Online Free',
    description: 'Convert HTML to Markdown instantly with clean output and syntax preservation. Features automatic formatting, table conversion, and code block handling. Perfect for content migration, documentation, and CMS integration. 100% client-side, free online converter.',
    path: '/html-to-markdown',
    keywords: [
      'html to markdown',
      'html to md',
      'convert html to markdown',
      'html markdown converter',
      'html parser markdown',
      'html to markdown online',
      'web to markdown',
      'html content converter',
      'markdown from html',
      'html syntax converter',
      'html table to markdown',
      'html code to markdown',
      'content migration tool',
      'cms to markdown',
      'html cleanup markdown',
      'reverse markdown',
      'html markdown parser',
      'html to md converter',
      'html formatting markdown',
      'best html to markdown',
    ],
    ogTitle: 'HTML to Markdown Converter - Convert HTML to MD Online',
    ogDescription: 'Convert HTML to Markdown instantly. Clean output, syntax preservation, table support. Free!',
    category: 'Data Conversion',
    priority: 0.8,
    changeFrequency: 'monthly',
    features: ['Clean output', 'Table conversion', 'Code blocks', 'Link preservation', 'Auto formatting'],
    useCases: ['Content migration', 'Documentation', 'CMS integration', 'Web scraping'],
    relatedTools: ['markdown-to-html', 'csv-to-json', 'xml-to-json', 'ascii-art'],
  },
  
  'base-converter': {
    title: 'Number Base Converter - Binary, Octal, Decimal, Hexadecimal Converter',
    description: 'Convert numbers between Binary (Base 2), Octal (Base 8), Decimal (Base 10), and Hexadecimal (Base 16) instantly. Features instant conversion to all bases, copy functionality, and support for large numbers. Perfect for programming, computer science, and digital electronics. Free online base converter.',
    path: '/base-converter',
    keywords: [
      'number base converter',
      'binary converter',
      'hex to decimal',
      'decimal to binary',
      'octal converter',
      'hexadecimal converter',
      'binary to decimal',
      'decimal to hex',
      'hex to binary',
      'base conversion',
      'number system converter',
      'binary calculator',
      'hex calculator',
      'octal to decimal',
      'binary to hex',
      'radix converter',
      'base 2 converter',
      'base 16 converter',
      'programmer calculator',
      'best base converter',
    ],
    ogTitle: 'Number Base Converter - Binary, Hex, Decimal, Octal',
    ogDescription: 'Convert between Binary, Octal, Decimal, Hexadecimal instantly. All bases at once, copy ready. Free!',
    category: 'Developer Tools',
    priority: 0.85,
    changeFrequency: 'monthly',
    features: ['All bases at once', 'Large number support', 'Copy to clipboard', 'Instant conversion', 'Error handling'],
    useCases: ['Programming', 'Computer science', 'Digital electronics', 'Debugging'],
    relatedTools: ['hash-generator', 'uuid-generator', 'timestamp-converter', 'color-converter'],
  },
  
  'case-converter': {
    title: 'Case Converter - camelCase, snake_case, kebab-case, PascalCase Converter',
    description: 'Convert text between camelCase, PascalCase, snake_case, kebab-case, CONSTANT_CASE, dot.case, and Title Case instantly. Features all case formats at once, copy functionality, and real-time conversion. Perfect for variable naming, API development, and code refactoring. Free online case converter.',
    path: '/case-converter',
    keywords: [
      'case converter',
      'camelcase to snake case',
      'snake case to camel case',
      'kebab case converter',
      'pascal case converter',
      'constant case',
      'camelcase converter',
      'snake_case converter',
      'kebab-case converter',
      'text case converter',
      'variable name converter',
      'naming convention converter',
      'string case converter',
      'camel to snake',
      'snake to camel',
      'pascal to camel',
      'title case converter',
      'dot case converter',
      'code naming converter',
      'best case converter',
    ],
    ogTitle: 'Case Converter - camelCase, snake_case, kebab-case',
    ogDescription: 'Convert between camelCase, snake_case, kebab-case, PascalCase instantly. All formats at once. Free!',
    category: 'Developer Tools',
    priority: 0.8,
    changeFrequency: 'monthly',
    features: ['7 case formats', 'Instant conversion', 'Copy to clipboard', 'Real-time preview', 'Batch support'],
    useCases: ['Variable naming', 'API development', 'Code refactoring', 'Database columns'],
    relatedTools: ['base-converter', 'url-encoder', 'ascii-art', 'regex-tester'],
  },
  
  'image-compressor': {
    title: 'Image Compressor - Compress Images Online Free (JPG, PNG, WebP)',
    description: 'Compress images with adjustable quality while maintaining visual clarity. Supports JPG, PNG, WebP formats with real-time size reduction preview. Features batch processing, format conversion, and EXIF preservation. 100% client-side processing - your images never leave your browser. Free tool.',
    path: '/image-compressor',
    keywords: [
      'image compressor',
      'compress image online',
      'reduce image size',
      'image optimizer',
      'compress jpg',
      'compress png',
      'webp converter',
      'image size reducer',
      'photo compressor',
      'bulk image compression',
      'lossless compression',
      'lossy compression',
      'image quality optimizer',
      'web image optimizer',
      'image file size reducer',
      'compress images for web',
      'email image compressor',
      'social media image optimizer',
      'website image optimizer',
      'best image compressor',
    ],
    ogTitle: 'Image Compressor - Compress Images Online Free',
    ogDescription: 'Compress JPG, PNG, WebP images instantly. Adjustable quality, size reduction preview. Free & secure!',
    category: 'Media Tools',
    priority: 0.8,
    changeFrequency: 'monthly',
    features: ['Quality adjustment', 'Multiple formats', 'Size preview', 'Batch processing', 'EXIF preservation'],
    useCases: ['Web optimization', 'Email attachments', 'Social media', 'Storage saving'],
    relatedTools: ['color-converter', 'qr-generator', 'ascii-art'],
  },
  
  'ascii-art': {
    title: 'ASCII Art Generator - Text to ASCII Art Online Free',
    description: 'Convert text to stunning ASCII art with multiple font styles including banner, block, and decorative fonts. Features instant preview, copy-to-clipboard, and supports special characters. Perfect for terminal headers, code comments, and creative projects. Free ASCII art generator.',
    path: '/ascii-art',
    keywords: [
      'ascii art generator',
      'text to ascii',
      'ascii art maker',
      'ascii text generator',
      'ascii banner',
      'ascii font generator',
      'figlet generator',
      'ascii logo maker',
      'terminal ascii art',
      'ascii code art',
      'ascii decoration',
      'text banner generator',
      'ascii word art',
      'ascii heading',
      'code comment art',
      'ascii signature',
      'ascii art styles',
      'big text generator',
      'monospace art',
      'best ascii generator',
    ],
    ogTitle: 'ASCII Art Generator - Text to ASCII Art Online',
    ogDescription: 'Convert text to ASCII art instantly. Multiple styles, instant preview, copy-ready. Free online tool!',
    category: 'Creative Tools',
    priority: 0.75,
    changeFrequency: 'monthly',
    features: ['Multiple fonts', 'Instant preview', 'Copy to clipboard', 'Special characters', 'Large text'],
    useCases: ['Terminal headers', 'Code comments', 'Creative projects', 'Documentation'],
    relatedTools: ['color-converter', 'qr-generator', 'image-compressor'],
  },
  
  'url-encoder': {
    title: 'URL Encoder & Decoder - Encode URLs Online Free',
    description: 'Encode and decode URLs, query strings, and URI components instantly. Features automatic detection, full/partial encoding options, and special character handling. Perfect for API testing, web development, and form data preparation. Free online URL encoder/decoder.',
    path: '/url-encoder',
    keywords: [
      'url encoder',
      'url decoder',
      'encode url online',
      'decode url online',
      'url escape',
      'url encode decode',
      'percent encoding',
      'uri encoder',
      'query string encoder',
      'url component encoder',
      'special character encoder',
      'url safe encoding',
      'rfc 3986 encoder',
      'javascript encodeuri',
      'encodeuricomponent',
      'url parameter encoder',
      'form data encoder',
      'base64 url encoding',
      'url parsing tool',
      'best url encoder',
    ],
    ogTitle: 'URL Encoder & Decoder - Encode URLs Online',
    ogDescription: 'Encode & decode URLs instantly. Query strings, special characters, API testing ready. Free tool!',
    category: 'Encoding Tools',
    priority: 0.8,
    changeFrequency: 'monthly',
    features: ['Auto detection', 'Full/partial encoding', 'Query string support', 'Copy to clipboard', 'History'],
    useCases: ['API testing', 'Web development', 'Form data', 'URL cleaning'],
    relatedTools: ['base64', 'regex-tester', 'qr-generator'],
  },
  
  'timestamp-converter': {
    title: 'Timestamp Converter - Unix Timestamp to Date & Time Online',
    description: 'Convert Unix timestamps to human-readable dates and vice versa. Supports multiple formats, timezone conversion, and relative time calculations. Features instant conversion, copy functionality, and timezone detection. Free online timestamp converter for developers.',
    path: '/timestamp-converter',
    keywords: [
      'timestamp converter',
      'unix timestamp',
      'epoch converter',
      'timestamp to date',
      'unix time converter',
      'epoch time',
      'convert timestamp',
      'milliseconds to date',
      'seconds to date',
      'iso 8601 converter',
      'utc timestamp',
      'timezone converter',
      'relative time',
      'date to timestamp',
      'unix epoch',
      'javascript timestamp',
      'mysql timestamp',
      'postgres timestamp',
      'timestamp formatter',
      'best timestamp converter',
    ],
    ogTitle: 'Timestamp Converter - Unix Timestamp to Date Online',
    ogDescription: 'Convert Unix timestamps to dates instantly. Multiple formats, timezone support, relative time. Free!',
    category: 'Utility Tools',
    priority: 0.8,
    changeFrequency: 'monthly',
    features: ['Multiple formats', 'Timezone support', 'Relative time', 'Bidirectional', 'Copy to clipboard'],
    useCases: ['Log analysis', 'Database work', 'API debugging', 'Server timestamps'],
    relatedTools: ['uuid-generator', 'hash-generator', 'jwt-decoder'],
  },
  
  'json-diff': {
    title: 'JSON Diff - Compare JSON Files & Objects Online Free',
    description: 'Compare two JSON objects side-by-side with visual highlighting of differences, additions, deletions, and modifications. Features nested comparison, array diffing, and merge suggestions. Perfect for API response comparison, config file diffing, and debugging. Free online JSON diff tool.',
    path: '/json-diff',
    keywords: [
      'json diff',
      'json compare',
      'compare json',
      'json difference',
      'json comparison tool',
      'diff json files',
      'json object compare',
      'json patch generator',
      'json merge tool',
      'api response compare',
      'config file diff',
      'json syntax diff',
      'nested json compare',
      'array diff json',
      'json visual diff',
      'json changelog',
      'json version compare',
      'deep json compare',
      'json delta viewer',
      'best json diff tool',
    ],
    ogTitle: 'JSON Diff - Compare JSON Objects Online',
    ogDescription: 'Compare JSON files side-by-side. Visual diff, nested support, merge suggestions. Free online tool!',
    category: 'JSON Tools',
    priority: 0.8,
    changeFrequency: 'monthly',
    features: ['Side-by-side view', 'Visual highlighting', 'Nested comparison', 'Array diffing', 'Merge suggestions'],
    useCases: ['API debugging', 'Config comparison', 'Version tracking', 'Data validation'],
    relatedTools: ['json-formatter', 'json-to-typescript', 'json-to-zod', 'validator'],
  },
  
  'validator': {
    title: 'Zod Validator - Validate JSON Data with Zod Schemas Online',
    description: 'Validate JSON data against Zod schemas with detailed error messages, type checking, and transformation support. Features real-time validation, custom error messages, and schema recommendations. Perfect for form validation, API testing, and data integrity checks. Free online Zod validator.',
    path: '/validator',
    keywords: [
      'zod validator',
      'schema validator',
      'json validator',
      'data validation',
      'zod validation online',
      'zod schema tester',
      'runtime validation',
      'typescript validation',
      'form validation tool',
      'api data validator',
      'json schema validator',
      'type checking online',
      'zod error messages',
      'zod transformation',
      'zod refinement',
      'zod custom validation',
      'zod typescript',
      'zod playground',
      'zod test tool',
      'best zod validator',
    ],
    ogTitle: 'Zod Validator - Validate Data with Zod Schemas',
    ogDescription: 'Validate JSON with Zod schemas instantly. Detailed errors, type checking, transformations. Free tool!',
    category: 'Validation Tools',
    priority: 0.8,
    changeFrequency: 'monthly',
    features: ['Real-time validation', 'Detailed errors', 'Type checking', 'Transformation support', 'Schema suggestions'],
    useCases: ['Form validation', 'API testing', 'Data integrity', 'Type checking'],
    relatedTools: ['json-to-zod', 'json-to-typescript', 'json-diff', 'json-formatter'],
  },
  
  'json-to-json-schema': {
    title: 'JSON to JSON Schema Generator - Create JSON Schemas Online',
    description: 'Generate JSON Schema (Draft 7, 2019-09, 2020-12) from JSON data automatically. Features type inference, validation rules, required field detection, and schema customization. Perfect for API documentation, data validation, and OpenAPI specs. Free JSON Schema generator.',
    path: '/json-to-json-schema',
    keywords: [
      'json to json schema',
      'json schema generator',
      'generate json schema',
      'json schema maker',
      'json schema creator',
      'json schema draft 7',
      'json schema 2019',
      'json schema 2020',
      'json validation schema',
      'openapi schema',
      'json schema inference',
      'json schema builder',
      'json schema online',
      'json schema validator',
      'json schema properties',
      'json schema required',
      'json schema types',
      'api schema generator',
      'json schema documentation',
      'best json schema generator',
    ],
    ogTitle: 'JSON to JSON Schema Generator - Create Schemas',
    ogDescription: 'Generate JSON Schema from JSON data instantly. Type inference, validation rules, OpenAPI ready. Free!',
    category: 'JSON Tools',
    priority: 0.75,
    changeFrequency: 'monthly',
    features: ['Type inference', 'Validation rules', 'Required fields', 'Multi-draft support', 'Schema customization'],
    useCases: ['API documentation', 'Data validation', 'OpenAPI specs', 'Schema design'],
    relatedTools: ['json-schema-to-typescript', 'json-to-typescript', 'json-to-zod', 'validator'],
  },
  
  'json-schema-to-typescript': {
    title: 'JSON Schema to TypeScript - Convert Schemas to TypeScript Types',
    description: 'Convert JSON Schema to TypeScript interfaces and types with full Draft 7/2019-09/2020-12 support. Features complex type handling, enum generation, and reference resolution. Perfect for API clients, type generation, and maintaining type safety. Free online converter.',
    path: '/json-schema-to-typescript',
    keywords: [
      'json schema to typescript',
      'schema to typescript',
      'json schema converter',
      'typescript from schema',
      'json schema types',
      'generate typescript from schema',
      'json schema interface',
      'json schema type generator',
      'openapi to typescript',
      'swagger to typescript',
      'json schema definitions',
      'json schema references',
      'json schema enums',
      'json schema union types',
      'json schema anyOf',
      'json schema oneOf',
      'json schema allOf',
      'complex schema converter',
      'json schema compiler',
      'best schema converter',
    ],
    ogTitle: 'JSON Schema to TypeScript - Convert Schemas to Types',
    ogDescription: 'Convert JSON Schema to TypeScript instantly. Full Draft support, complex types, enum generation. Free!',
    category: 'JSON Tools',
    priority: 0.75,
    changeFrequency: 'monthly',
    features: ['Full Draft support', 'Complex types', 'Enum generation', 'Reference resolution', 'Interface naming'],
    useCases: ['API clients', 'Type generation', 'Schema migration', 'Type safety'],
    relatedTools: ['json-to-json-schema', 'json-to-typescript', 'typescript-to-zod', 'zod-to-typescript'],
  },
  
  'typescript-to-zod': {
    title: 'TypeScript to Zod - Convert TS Types to Zod Schemas Online',
    description: 'Convert TypeScript types, interfaces, and enums to Zod validation schemas automatically. Features generic support, union types, and complex type handling. Perfect for adding runtime validation to existing TypeScript projects. Free online TypeScript to Zod converter.',
    path: '/typescript-to-zod',
    keywords: [
      'typescript to zod',
      'ts to zod',
      'convert typescript to zod',
      'zod from typescript',
      'interface to zod',
      'typescript zod converter',
      'generate zod from ts',
      'type to zod schema',
      'typescript runtime validation',
      'zod schema from interface',
      'typescript enum to zod',
      'typescript union to zod',
      'generic types zod',
      'typescript zod generator',
      'zod inference from ts',
      'ts types to validators',
      'typescript validation schema',
      'zod schema builder',
      'type safe validation',
      'best ts to zod converter',
    ],
    ogTitle: 'TypeScript to Zod - Convert TS Types to Zod Schemas',
    ogDescription: 'Convert TypeScript to Zod schemas instantly. Generic support, unions, complex types. Free online tool!',
    category: 'Validation Tools',
    priority: 0.75,
    changeFrequency: 'monthly',
    features: ['Generic support', 'Union types', 'Enum conversion', 'Complex types', 'Interface support'],
    useCases: ['Runtime validation', 'Type migration', 'Schema creation', 'Type safety'],
    relatedTools: ['zod-to-typescript', 'json-to-zod', 'json-to-typescript', 'validator'],
  },
  
  'zod-to-typescript': {
    title: 'Zod to TypeScript - Extract Types from Zod Schemas Online',
    description: 'Extract TypeScript types, interfaces, and enums from Zod validation schemas automatically. Features type inference, generic preservation, and complex schema support. Perfect for documentation generation and maintaining type consistency. Free online Zod to TypeScript converter.',
    path: '/zod-to-typescript',
    keywords: [
      'zod to typescript',
      'zod to ts',
      'extract zod types',
      'typescript from zod',
      'zod schema to interface',
      'zod type inference',
      'zod to type',
      'generate typescript from zod',
      'zod typescript export',
      'zod to type alias',
      'zod interface generator',
      'zod types extraction',
      'zod to ts types',
      'zod schema types',
      'zod type definitions',
      'zod documentation',
      'zod type generator',
      'zod inference helper',
      'zod schema converter',
      'best zod to ts converter',
    ],
    ogTitle: 'Zod to TypeScript - Extract Types from Zod Schemas',
    ogDescription: 'Extract TypeScript types from Zod schemas instantly. Type inference, generics, complex schemas. Free tool!',
    category: 'Validation Tools',
    priority: 0.75,
    changeFrequency: 'monthly',
    features: ['Type inference', 'Generic preservation', 'Enum extraction', 'Complex schemas', 'Documentation'],
    useCases: ['Type extraction', 'Documentation', 'Type consistency', 'Schema sharing'],
    relatedTools: ['typescript-to-zod', 'json-to-zod', 'json-to-typescript', 'validator'],
  },
  
  'json-path': {
    title: 'JSONPath Query Tool - Extract & Filter JSON Data Online',
    description: 'Query and extract data from JSON using JSONPath expressions. Features wildcard support, filters, array slicing, recursive descent, and visual tree view. Supports complex queries like $.store.book[?(@.price<10)]. 100% client-side, free, and privacy-focused. The most powerful JSONPath tool online.',
    path: '/json-path',
    keywords: [
      'jsonpath',
      'json path query',
      'jsonpath online',
      'json path expression',
      'json query language',
      'extract json data',
      'json filter',
      'json path selector',
      'jsonpath tutorial',
      'jsonpath examples',
      'jsonpath wildcards',
      'jsonpath filter',
      'jsonpath array',
      'jsonpath recursive',
      'json data extraction',
      'query json online',
      'json selector',
      'json xpath',
      'json path finder',
      'best jsonpath tool',
    ],
    ogTitle: 'JSONPath Query Tool - Extract JSON Data with Expressions',
    ogDescription: 'Query JSON data with JSONPath expressions. Wildcards, filters, slicing, recursive descent. Free, client-side, powerful!',
    category: 'JSON Tools',
    priority: 0.92,
    changeFrequency: 'monthly',
    features: ['Wildcards (*)', 'Filter expressions', 'Array slicing', 'Recursive descent', 'Visual results', 'Copy results'],
    useCases: ['Data extraction', 'API response filtering', 'JSON analysis', 'Data transformation', 'Configuration parsing'],
    relatedTools: ['json-formatter', 'json-diff', 'validator', 'json-to-typescript'],
  },
  
  'html-entities': {
    title: 'HTML Entity Encoder/Decoder - Convert Special Characters Online',
    description: 'Encode and decode HTML entities instantly. Convert special characters like <, >, &, " to &lt;, &gt;, &amp;, &quot; and vice versa. Features visual preview, common entities reference, and supports all Unicode characters including symbols (©, €, £, ¥). 100% client-side, free, and privacy-focused.',
    path: '/html-entities',
    keywords: [
      'html entity encoder',
      'html entity decoder',
      'html entities converter',
      'encode html entities',
      'decode html entities',
      'html special characters',
      'html escape',
      'html unescape',
      'html entity reference',
      'unicode to html entity',
      'html symbol encoder',
      'html character codes',
      'html entity table',
      'html encoding online',
      'html decoding online',
      'escape html special chars',
      'convert to html entities',
      'html entity cheat sheet',
      'xss prevention encode',
      'best html entity tool',
    ],
    ogTitle: 'HTML Entity Encoder/Decoder - Convert Special Characters',
    ogDescription: 'Encode/decode HTML entities instantly. < > & " to entities, Unicode support, visual preview. Free & client-side!',
    category: 'Encoding Tools',
    priority: 0.88,
    changeFrequency: 'monthly',
    features: ['Encode/Decode', 'Visual preview', 'Common entities reference', 'Unicode support', 'Copy to clipboard'],
    useCases: ['XSS prevention', 'HTML code display', 'Special character handling', 'Email templates', 'Web development'],
    relatedTools: ['url-encoder', 'base64', 'markdown-to-html', 'html-to-markdown'],
  },
  
  'unicode-escape': {
    title: 'Unicode Escape/Unescape - Convert Unicode Characters Online',
    description: 'Escape and unescape Unicode characters to \\uXXXX or \\u{XXXXXX} format. Supports emojis, special symbols, and all Unicode planes. Features multiple escape modes, JavaScript code examples, and instant conversion. Perfect for internationalization, debugging encoding issues, and working with special characters.',
    path: '/unicode-escape',
    keywords: [
      'unicode escape',
      'unicode unescape',
      'unicode converter',
      'escape unicode characters',
      'unescape unicode',
      'unicode to escape sequence',
      'emoji escape',
      'special character escape',
      'unicode escape online',
      'unicode escape javascript',
      'unicode escape sequence',
      '\\uXXXX converter',
      'unicode hex escape',
      'unicode string escape',
      'character encoding escape',
      'unicode notation',
      'escape non-ascii',
      'unicode code points',
      'escape special symbols',
      'best unicode tool',
    ],
    ogTitle: 'Unicode Escape/Unescape - Convert Special Characters',
    ogDescription: 'Escape Unicode to \\uXXXX format. Emojis, symbols, all planes. JS examples, instant conversion. Free!',
    category: 'Encoding Tools',
    priority: 0.85,
    changeFrequency: 'monthly',
    features: ['\\uXXXX escape', '\\u{XXXXXX} escape', 'Hex escape (\\xXX)', 'Unescape', 'JS code examples'],
    useCases: ['Internationalization', 'Debugging encoding', 'Special characters', 'Source code', 'API integration'],
    relatedTools: ['html-entities', 'url-encoder', 'base64', 'json-formatter'],
  },
  
  'json-to-csv': {
    title: 'JSON to CSV Converter - Convert JSON Arrays to CSV Online',
    description: 'Convert JSON arrays to CSV format instantly with automatic header detection, nested object flattening, and multiple delimiter options. Features table preview, column selection, and RFC 4180 compliant escaping. Supports comma, tab, semicolon, and pipe delimiters. 100% client-side, free, and handles large files.',
    path: '/json-to-csv',
    keywords: [
      'json to csv',
      'convert json to csv',
      'json csv converter',
      'json array to csv',
      'export json to csv',
      'json to spreadsheet',
      'json to excel',
      'flatten json to csv',
      'nested json to csv',
      'json csv export online',
      'convert json data to csv',
      'json flat file',
      'csv delimiter options',
      'json table converter',
      'api to csv',
      'data export csv',
      'json flatten tool',
      'convert api response to csv',
      'json dataset to csv',
      'best json csv converter',
    ],
    ogTitle: 'JSON to CSV Converter - Convert Arrays to CSV Online',
    ogDescription: 'Convert JSON to CSV instantly. Flatten nested objects, multiple delimiters, table preview. Free!',
    category: 'Converters',
    priority: 0.9,
    changeFrequency: 'monthly',
    features: ['Array conversion', 'Flatten objects', 'Multiple delimiters', 'Table preview', 'RFC 4180 compliant'],
    useCases: ['Data export', 'Excel import', 'Database export', 'API data conversion', 'Spreadsheet creation'],
    relatedTools: ['csv-to-json', 'json-formatter', 'json-diff', 'validator'],
  },
  
  'json-minify': {
    title: 'JSON Minifier - Compress & Minify JSON Online',
    description: 'Minify and compress JSON to reduce file size. Remove whitespace, optimize formatting, and validate JSON structure. Features one-click minification, size comparison, and minified output validation. Perfect for API responses, configuration files, and production deployments. 100% client-side, free, and privacy-focused.',
    path: '/json-minify',
    keywords: [
      'json minifier',
      'minify json',
      'compress json',
      'json minification',
      'json optimizer',
      'reduce json size',
      'json compression',
      'compact json',
      'json minify online',
      'json file size reducer',
      'minified json generator',
      'remove json whitespace',
      'json one line',
      'json smaller file',
      'json production ready',
      'json api optimization',
      'json config minify',
      'json bundle size',
      'json performance',
      'best json minifier',
    ],
    ogTitle: 'JSON Minifier - Compress JSON & Reduce Size',
    ogDescription: 'Minify JSON instantly. Remove whitespace, validate, size comparison. Perfect for production. Free!',
    category: 'JSON Tools',
    priority: 0.87,
    changeFrequency: 'monthly',
    features: ['Remove whitespace', 'Size comparison', 'Validation', 'One-click minify', 'Copy output'],
    useCases: ['API optimization', 'Production deployment', 'File size reduction', 'Configuration files', 'Web performance'],
    relatedTools: ['json-formatter', 'validator', 'json-to-typescript', 'json-to-csv'],
  },
  
  'curl-to-fetch': {
    title: 'cURL to Fetch/Axios/Node.js Converter - API Code Generator',
    description: 'Convert cURL commands to Fetch API, Axios, or Node.js HTTPS code instantly. Supports headers, methods, request bodies, and multi-line commands. Perfect for testing APIs, converting documentation examples, and generating JavaScript/TypeScript code. 100% client-side, free, and privacy-focused.',
    path: '/curl-to-fetch',
    keywords: [
      'curl to fetch',
      'curl to axios',
      'curl converter',
      'curl to javascript',
      'curl to nodejs',
      'convert curl command',
      'api code generator',
      'curl to http request',
      'curl to fetch api',
      'curl command converter',
      'curl parse online',
      'curl to code',
      'api testing tool',
      'http request generator',
      'curl javascript converter',
      'curl typescript',
      'curl axios converter',
      'curl postman alternative',
      'api client generator',
      'best curl converter',
    ],
    ogTitle: 'cURL to Fetch/Axios/Node.js - API Code Generator',
    ogDescription: 'Convert cURL to Fetch, Axios, or Node.js instantly. Headers, methods, body support. Free!',
    category: 'Developer Tools',
    priority: 0.91,
    changeFrequency: 'monthly',
    features: ['Fetch API', 'Axios', 'Node.js HTTPS', 'Header parsing', 'Body support', 'Multi-line commands'],
    useCases: ['API testing', 'Code generation', 'Documentation', 'Postman alternative', 'Development'],
    relatedTools: ['url-parser', 'jwt-decoder', 'validator', 'json-formatter'],
  },
  
  'toml-to-json': {
    title: 'TOML to JSON Converter - Parse TOML Config Files Online',
    description: 'Convert TOML configuration files to JSON format instantly. Parse TOML syntax including tables, arrays, inline tables, and datetime values. Perfect for working with pyproject.toml, Cargo.toml, and other config files. 100% client-side, free, and privacy-focused.',
    path: '/toml-to-json',
    keywords: [
      'toml to json',
      'toml parser',
      'toml converter',
      'parse toml online',
      'toml to object',
      'toml config parser',
      'pyproject.toml to json',
      'cargo.toml parser',
      'toml configuration',
      'toml file converter',
      'toml syntax parser',
      'toml tables',
      'toml arrays',
      'toml datetime',
      'toml inline tables',
      'config file converter',
      'toml validator',
      'toml format online',
      'rust toml parser',
      'best toml converter',
    ],
    ogTitle: 'TOML to JSON Converter - Parse Config Files',
    ogDescription: 'Convert TOML to JSON instantly. Tables, arrays, inline tables, datetime. Free & client-side!',
    category: 'Converters',
    priority: 0.85,
    changeFrequency: 'monthly',
    features: ['Full TOML support', 'Tables', 'Arrays', 'Inline tables', 'Datetime values', 'Validation'],
    useCases: ['Config files', 'pyproject.toml', 'Cargo.toml', 'TOML editing', 'Data conversion'],
    relatedTools: ['json-to-toml', 'yaml-to-json', 'xml-to-json', 'validator'],
  },
  
  'json-to-toml': {
    title: 'JSON to TOML Converter - Generate TOML from JSON',
    description: 'Convert JSON to TOML configuration format instantly. Generate clean, readable TOML with proper table structure, inline tables for small objects, and array formatting. Perfect for creating configuration files for Python, Rust, and other TOML-based projects. 100% client-side, free, and privacy-focused.',
    path: '/json-to-toml',
    keywords: [
      'json to toml',
      'json to toml converter',
      'generate toml',
      'json to config',
      'create toml file',
      'json toml generator',
      'convert json to toml',
      'toml config generator',
      'json object to toml',
      'api to toml',
      'json to pyproject.toml',
      'json to cargo.toml',
      'toml output generator',
      'json toml online',
      'json toml tool',
      'toml file creator',
      'config file generator',
      'json to toml format',
      'best json toml converter',
    ],
    ogTitle: 'JSON to TOML Converter - Generate Config Files',
    ogDescription: 'Convert JSON to TOML instantly. Clean tables, inline formatting, readable output. Free!',
    category: 'Converters',
    priority: 0.85,
    changeFrequency: 'monthly',
    features: ['Clean output', 'Table structure', 'Inline tables', 'Array formatting', 'Validation'],
    useCases: ['Config creation', 'pyproject.toml', 'Cargo.toml', 'TOML generation', 'Data conversion'],
    relatedTools: ['toml-to-json', 'yaml-to-json', 'json-to-yaml', 'validator'],
  },
  
  'user-agent-parser': {
    title: 'User Agent Parser - Browser & Device Detection',
    description: 'Parse User-Agent strings to detect browser, operating system, device type, and engine information. Features detailed breakdown, device detection, and browser version parsing. Perfect for analytics, debugging, and compatibility testing. 100% client-side, free, and privacy-focused.',
    path: '/user-agent-parser',
    keywords: [
      'user agent parser',
      'user agent detector',
      'browser detection',
      'device detection',
      'os detection',
      'parse user agent',
      'user agent string',
      'browser version',
      'mobile detection',
      'tablet detection',
      'user agent analyzer',
      'ua parser online',
      'user agent info',
      'browser info',
      'device info',
      'operating system detection',
      'user agent breakdown',
      'client detection',
      'user agent tool',
      'best user agent parser',
    ],
    ogTitle: 'User Agent Parser - Detect Browser & Device',
    ogDescription: 'Parse User-Agent strings instantly. Browser, OS, device detection. Detailed breakdown. Free!',
    category: 'Developer Tools',
    priority: 0.88,
    changeFrequency: 'monthly',
    features: ['Browser detection', 'OS detection', 'Device type', 'Engine info', 'Version parsing', 'Mobile detection'],
    useCases: ['Analytics', 'Debugging', 'Compatibility', 'Device targeting', 'Testing'],
    relatedTools: ['url-parser', 'regex-tester', 'validator', 'timestamp-converter'],
  },
  
  'semver-checker': {
    title: 'Semver Checker - Semantic Version Comparison & Validation',
    description: 'Compare and validate semantic versions (semver) with support for ranges, prerelease tags, and build metadata. Check version compatibility, compare versions, and validate version strings. Perfect for package management, dependency checking, and CI/CD pipelines. 100% client-side, free, and privacy-focused.',
    path: '/semver-checker',
    keywords: [
      'semver checker',
      'semantic version',
      'version comparison',
      'semver validator',
      'compare versions',
      'npm version check',
      'package version',
      'version range',
      'semver online',
      'version compatibility',
      'prerelease version',
      'version constraint',
      'semver parser',
      'version matcher',
      'satisfies semver',
      'semver calculator',
      'version checker tool',
      'dependency version',
      'semver validation',
      'best semver tool',
    ],
    ogTitle: 'Semver Checker - Version Comparison & Validation',
    ogDescription: 'Compare semantic versions instantly. Ranges, prerelease, compatibility check. Free!',
    category: 'Developer Tools',
    priority: 0.86,
    changeFrequency: 'monthly',
    features: ['Version comparison', 'Range checking', 'Prerelease support', 'Validation', 'Compatibility check'],
    useCases: ['Package management', 'Dependency checking', 'CI/CD', 'Version planning', 'Release management'],
    relatedTools: ['validator', 'json-formatter', 'timestamp-converter', 'url-parser'],
  },
  
  'json-to-env': {
    title: 'JSON to ENV Converter - Generate Environment Variables',
    description: 'Convert JSON to .env file format instantly. Generate environment variables from JSON objects with customizable prefixes, uppercase keys, and value formatting. Perfect for configuration management, Docker environments, and application deployment. 100% client-side, free, and privacy-focused.',
    path: '/json-to-env',
    keywords: [
      'json to env',
      'json to environment variables',
      'json to dotenv',
      'json config to env',
      'convert json to env',
      'json env generator',
      'env file creator',
      'environment variables generator',
      'json to .env',
      'config to env',
      'api to env',
      'json env converter',
      'env variable tool',
      'dotenv generator',
      'env file from json',
      'docker env generator',
      'application config env',
      'deployment env vars',
      'json environment config',
      'best json env converter',
    ],
    ogTitle: 'JSON to ENV Converter - Generate Environment Variables',
    ogDescription: 'Convert JSON to .env instantly. Custom prefixes, uppercase keys, value formatting. Free!',
    category: 'Converters',
    priority: 0.87,
    changeFrequency: 'monthly',
    features: ['Custom prefixes', 'Uppercase keys', 'Value formatting', 'Nested objects', 'Validation'],
    useCases: ['Configuration', 'Docker env', 'Deployment', 'App settings', 'Environment setup'],
    relatedTools: ['json-formatter', 'json-to-csv', 'yaml-to-json', 'validator'],
  },
  
  'css-box-shadow': {
    title: 'CSS Box Shadow Generator - Visual Shadow Builder',
    description: 'Create beautiful CSS box shadows with a visual editor. Adjust offset, blur, spread, color, and inset options. Features real-time preview, multiple shadows, presets, and copy-paste ready CSS code. Perfect for web design, UI development, and prototyping. 100% client-side, free, and privacy-focused.',
    path: '/css-box-shadow',
    keywords: [
      'css box shadow generator',
      'box shadow creator',
      'shadow css generator',
      'box shadow visual editor',
      'css shadow maker',
      'box shadow tool',
      'shadow effect generator',
      'css drop shadow',
      'inner shadow generator',
      'multiple shadows css',
      'box shadow presets',
      'shadow designer',
      'css shadow builder',
      'ui shadow generator',
      'material design shadow',
      'elevation shadow css',
      'shadow code generator',
      'css3 shadow tool',
      'shadow preview online',
      'best box shadow generator',
    ],
    ogTitle: 'CSS Box Shadow Generator - Visual Builder',
    ogDescription: 'Create CSS box shadows visually. Real-time preview, multiple shadows, presets. Free!',
    category: 'Design Tools',
    priority: 0.89,
    changeFrequency: 'monthly',
    features: ['Visual editor', 'Real-time preview', 'Multiple shadows', 'Color picker', 'Presets', 'Copy CSS'],
    useCases: ['Web design', 'UI development', 'Prototyping', 'Shadow effects', 'Material design'],
    relatedTools: ['css-gradient', 'color-converter', 'qr-generator', 'image-compressor'],
  },
  
  'css-gradient': {
    title: 'CSS Gradient Generator - Create Beautiful Gradients',
    description: 'Create stunning CSS gradients with a visual editor. Support for linear, radial, and conic gradients with multiple color stops, angles, and positions. Features real-time preview, presets, and copy-paste ready CSS code. Perfect for web design, backgrounds, and creative projects. 100% client-side, free, and privacy-focused.',
    path: '/css-gradient',
    keywords: [
      'css gradient generator',
      'gradient creator',
      'linear gradient css',
      'radial gradient generator',
      'conic gradient css',
      'gradient maker',
      'css gradient tool',
      'background gradient',
      'gradient designer',
      'multi color gradient',
      'gradient preview',
      'css3 gradient generator',
      'gradient code generator',
      'color gradient tool',
      'gradient builder',
      'web gradient creator',
      'ui gradient generator',
      'gradient presets',
      'gradient angles',
      'best gradient generator',
    ],
    ogTitle: 'CSS Gradient Generator - Create Beautiful Gradients',
    ogDescription: 'Create CSS gradients visually. Linear, radial, conic. Real-time preview, presets. Free!',
    category: 'Design Tools',
    priority: 0.89,
    changeFrequency: 'monthly',
    features: ['Linear gradients', 'Radial gradients', 'Conic gradients', 'Multi-stop', 'Real-time preview', 'Presets'],
    useCases: ['Web design', 'Backgrounds', 'UI design', 'Creative projects', 'Branding'],
    relatedTools: ['css-box-shadow', 'color-converter', 'qr-generator', 'image-compressor'],
  },
};

export const toolsMetadata: Record<string, Metadata> = Object.fromEntries(
  Object.entries(toolsData).map(([key, data]) => [
    key,
    generatePageMetadata(data),
  ])
);

export function getToolMetadata(toolId: string): Metadata {
  return toolsMetadata[toolId] || toolsMetadata['json-to-typescript'];
}

export function getToolInfo(toolId: string): ToolInfo | undefined {
  return toolsData[toolId];
}

export function getAllTools(): ToolInfo[] {
  return Object.values(toolsData);
}

export function getRelatedTools(toolId: string): ToolInfo[] {
  const tool = toolsData[toolId];
  if (!tool) return [];
  
  return tool.relatedTools
    .map(id => toolsData[id])
    .filter(Boolean) as ToolInfo[];
}

export function getToolsByCategory(category: string): ToolInfo[] {
  return Object.values(toolsData).filter(tool => tool.category === category);
}

export function getAllCategories(): string[] {
  const categories = new Set(Object.values(toolsData).map(tool => tool.category));
  return Array.from(categories).sort();
}
