import { Metadata } from 'next';
import { generatePageMetadata, ToolMetadata } from './metadata';

export interface ToolInfo extends ToolMetadata {
  category: string;
  priority: number;
  changeFrequency: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
  features: string[];
  useCases: string[];
  relatedTools: string[];
}

export const toolsData: Record<string, ToolInfo> = {
  'json-to-typescript': {
    title: 'JSON to TypeScript Converter - Generate TypeScript Interfaces & Types Instantly',
    description: 'Convert JSON to TypeScript interfaces and types instantly with our powerful converter. Features intelligent type inference, supports multiple JSON samples, generates nested interfaces, and creates mock data. 100% free, client-side processing - your data never leaves your browser. Perfect for API integration and type-safe development.',
    path: '/json-to-typescript',
    keywords: [
      'json to typescript converter',
      'typescript interface generator',
      'json to ts',
      'typescript types from json',
      'automatic type inference',
      'generate typescript interfaces',
      'json to typescript online',
      'typescript type generator',
      'json parser to typescript',
      'typescript interface from json object',
      'convert json response to typescript',
      'api typescript types generator',
      'json schema typescript',
      'typescript model generator',
      'json to typescript class',
      'json to interface typescript',
      'generate types from api response',
      'typescript code generation',
      'json type inference',
      'best json to typescript converter',
    ],
    ogTitle: 'Best JSON to TypeScript Converter - Generate Types Instantly',
    ogDescription: 'Transform JSON to TypeScript interfaces instantly. Smart type inference, multi-sample support, 100% client-side & free.',
    category: 'JSON Tools',
    priority: 1.0,
    changeFrequency: 'weekly',
    features: ['Type inference', 'Multi-sample support', 'Nested interfaces', 'Mock data generation', 'Interface naming'],
    useCases: ['API integration', 'Type-safe development', 'Frontend-backend sync', 'Documentation generation'],
    relatedTools: ['json-to-zod', 'json-to-json-schema', 'json-schema-to-typescript', 'typescript-to-zod'],
  },
  
  'json-to-zod': {
    title: 'JSON to Zod Schema Generator - Create Runtime Validation Schemas',
    description: 'Generate Zod validation schemas from JSON data automatically. Create runtime type-safe schemas with intelligent type inference, custom validations, and full TypeScript integration. Perfect for form validation, API validation, and data sanitization. Free, privacy-focused, works offline.',
    path: '/json-to-zod',
    keywords: [
      'json to zod',
      'zod schema generator',
      'zod validation schema',
      'runtime validation',
      'type-safe validation',
      'zod from json',
      'generate zod schema',
      'zod typescript validation',
      'json to zod online',
      'zod schema creator',
      'automatic zod generation',
      'zod validator generator',
      'form validation zod',
      'api validation zod',
      'zod schema from api',
      'typescript zod converter',
      'zod type inference',
      'json schema to zod',
      'zod object validation',
      'best zod generator',
    ],
    ogTitle: 'JSON to Zod Schema Generator - Runtime Type Validation',
    ogDescription: 'Generate Zod schemas from JSON instantly. Runtime validation with TypeScript integration. Free & client-side.',
    category: 'Validation Tools',
    priority: 0.95,
    changeFrequency: 'weekly',
    features: ['Type inference', 'Custom validations', 'Nested schemas', 'Enum support', 'Optional fields'],
    useCases: ['Form validation', 'API validation', 'Data sanitization', 'Runtime type checking'],
    relatedTools: ['json-to-typescript', 'validator', 'typescript-to-zod', 'zod-to-typescript'],
  },
  
  'json-formatter': {
    title: 'JSON Formatter & Validator - Beautify, Prettify & Minify JSON Online',
    description: 'Format, validate, beautify, and minify JSON with our professional online formatter. Features syntax highlighting, real-time error detection, JSON sorting, and tree view. Handles large JSON files with ease. No data sent to servers - 100% client-side processing. Free developer tool.',
    path: '/json-formatter',
    keywords: [
      'json formatter',
      'json beautifier',
      'json validator',
      'json minifier',
      'prettify json',
      'format json online',
      'json pretty print',
      'json lint',
      'json parser online',
      'validate json online',
      'json syntax highlighter',
      'json tree viewer',
      'json editor online',
      'json string formatter',
      'compress json',
      'json unminify',
      'online json tool',
      'json checker',
      'json validation tool',
      'best json formatter',
    ],
    ogTitle: 'JSON Formatter & Validator - Free Online Tool',
    ogDescription: 'Format, validate & beautify JSON instantly. Syntax highlighting, error detection, 100% client-side. Try now!',
    category: 'JSON Tools',
    priority: 0.9,
    changeFrequency: 'monthly',
    features: ['Syntax highlighting', 'Error detection', 'Sort keys', 'Minify/Beautify', 'Tree view'],
    useCases: ['Debugging APIs', 'Config file editing', 'Data visualization', 'JSON editing'],
    relatedTools: ['json-to-typescript', 'json-to-zod', 'json-diff', 'validator'],
  },
  
  'regex-tester': {
    title: 'RegEx Tester & Debugger - Test Regular Expressions Online Free',
    description: 'Test, debug, and build regular expressions with live match highlighting. Supports all JavaScript regex flags (g, i, m, s, u, y), capture groups, and replacements. Perfect for pattern matching, data validation, and string manipulation. Free online regex tester with instant results.',
    path: '/regex-tester',
    keywords: [
      'regex tester',
      'regular expression tester',
      'regex validator',
      'regex match online',
      'regex debugger',
      'test regular expressions',
      'regex online tool',
      'regex builder',
      'javascript regex tester',
      'regex pattern matcher',
      'regex flags tester',
      'regex capture groups',
      'regex replace online',
      'regex cheat sheet',
      'regex playground',
      'online regex editor',
      'regex validator tool',
      'regular expression debugger',
      'test regex patterns',
      'best regex tester',
    ],
    ogTitle: 'RegEx Tester - Test Regular Expressions Online',
    ogDescription: 'Test & debug regex patterns instantly. Live matching, all flags supported, capture groups. Free tool!',
    category: 'Developer Tools',
    priority: 0.9,
    changeFrequency: 'monthly',
    features: ['Live matching', 'All flags support', 'Capture groups', 'Replace mode', 'Pattern explanation'],
    useCases: ['Form validation', 'Data parsing', 'Search & replace', 'Pattern extraction'],
    relatedTools: ['validator', 'url-encoder', 'base64'],
  },
  
  'base64': {
    title: 'Base64 Encoder & Decoder - Convert Base64 Online Free',
    description: 'Encode and decode Base64 strings instantly with our secure online converter. Supports text, files, and URLs. Bidirectional conversion with copy-to-clipboard functionality. 100% client-side processing ensures your data stays private. Free Base64 encoder/decoder tool.',
    path: '/base64',
    keywords: [
      'base64 encoder',
      'base64 decoder',
      'base64 converter',
      'encode base64',
      'decode base64',
      'base64 online tool',
      'base64 text encoder',
      'base64 file encoder',
      'base64 url encoder',
      'base64 decode online',
      'base64 to text',
      'text to base64',
      'base64 encoder decoder',
      'base64 string converter',
      'javascript base64',
      'atob btoa online',
      'base64 encryption',
      'base64 data uri',
      'base64 image encoder',
      'best base64 tool',
    ],
    ogTitle: 'Base64 Encoder & Decoder - Free Online Tool',
    ogDescription: 'Encode & decode Base64 instantly. Text, files, URLs supported. 100% client-side, secure & free.',
    category: 'Encoding Tools',
    priority: 0.85,
    changeFrequency: 'monthly',
    features: ['Text encoding', 'File support', 'URL safe', 'Copy to clipboard', 'History'],
    useCases: ['Data transmission', 'URL parameters', 'Image embedding', 'API authentication'],
    relatedTools: ['url-encoder', 'jwt-decoder', 'hash-generator'],
  },
  
  'color-converter': {
    title: 'Color Converter - HEX to RGB, RGB to HSL, Color Picker Tool',
    description: 'Convert colors between HEX, RGB, HSL, RGBA, and HSLA formats instantly. Features visual color picker, color palette generation, contrast checker, and CSS output. Perfect for web designers and developers. Free online color converter with instant previews.',
    path: '/color-converter',
    keywords: [
      'color converter',
      'hex to rgb',
      'rgb to hex',
      'rgb to hsl',
      'hsl converter',
      'color picker online',
      'hex color converter',
      'rgb color code',
      'hsl color picker',
      'color code translator',
      'css color converter',
      'rgba converter',
      'hex to rgba',
      'color palette generator',
      'contrast checker',
      'web color tool',
      'designer color tool',
      'color format converter',
      'hexadecimal converter',
      'best color converter',
    ],
    ogTitle: 'Color Converter - HEX, RGB, HSL Converter with Picker',
    ogDescription: 'Convert colors between HEX, RGB, HSL instantly. Color picker, palette generator, CSS output. Free!',
    category: 'Design Tools',
    priority: 0.85,
    changeFrequency: 'monthly',
    features: ['Visual picker', 'Multi-format support', 'Palette generation', 'Contrast checker', 'CSS output'],
    useCases: ['Web design', 'CSS styling', 'Brand colors', 'Accessibility testing'],
    relatedTools: ['qr-generator', 'image-compressor', 'ascii-art'],
  },
  
  'qr-generator': {
    title: 'QR Code Generator - Create QR Codes Online Free',
    description: 'Generate QR codes from any text, URL, contact info, or WiFi credentials. Features custom colors, error correction levels, multiple formats (PNG, SVG), and instant download. Works offline, no tracking, 100% free. Perfect for marketing, business cards, and digital payments.',
    path: '/qr-generator',
    keywords: [
      'qr code generator',
      'qr generator free',
      'create qr code online',
      'qr code maker',
      'free qr code',
      'generate qr code',
      'qr code creator',
      'url to qr code',
      'text to qr code',
      'wifi qr code generator',
      'vcard qr code',
      'custom qr code',
      'qr code designer',
      'bulk qr generator',
      'dynamic qr code',
      'static qr code',
      'qr code png',
      'qr code svg',
      'marketing qr codes',
      'best qr generator',
    ],
    ogTitle: 'QR Code Generator - Create QR Codes Free Online',
    ogDescription: 'Generate QR codes for URLs, text, WiFi & more. Custom colors, instant download. Free & offline!',
    category: 'Utility Tools',
    priority: 0.85,
    changeFrequency: 'monthly',
    features: ['Custom colors', 'Error correction', 'Multiple formats', 'WiFi/Contact support', 'Instant download'],
    useCases: ['Marketing materials', 'Business cards', 'Digital payments', 'Product labeling'],
    relatedTools: ['color-converter', 'url-encoder', 'base64'],
  },
  
  'uuid-generator': {
    title: 'UUID Generator - Generate UUIDs v1, v4, v5, v7 Online',
    description: 'Generate UUIDs and GUIDs instantly with support for multiple versions (v1, v4, v5, v7). Features bulk generation, custom namespace support, and cryptographically secure random generation. Free online UUID generator for developers and system architects.',
    path: '/uuid-generator',
    keywords: [
      'uuid generator',
      'guid generator',
      'uuid v4 generator',
      'uuid v1',
      'uuid v7',
      'generate uuid online',
      'bulk uuid generator',
      'random uuid generator',
      'unique id generator',
      'guid creator',
      'uuid javascript',
      'uuid npm',
      'uuid library',
      'universal unique identifier',
      'globally unique identifier',
      'uuid format',
      'uuid validator',
      'custom uuid',
      'namespace uuid',
      'best uuid generator',
    ],
    ogTitle: 'UUID Generator - Generate UUIDs v1, v4, v5, v7 Online',
    ogDescription: 'Generate UUIDs & GUIDs instantly. Multiple versions, bulk generation, secure random. Free tool!',
    category: 'Developer Tools',
    priority: 0.85,
    changeFrequency: 'monthly',
    features: ['Multiple versions', 'Bulk generation', 'Secure random', 'Custom namespace', 'Copy all'],
    useCases: ['Database IDs', 'API keys', 'Session tokens', 'Distributed systems'],
    relatedTools: ['hash-generator', 'jwt-decoder', 'timestamp-converter'],
  },
  
  'hash-generator': {
    title: 'Hash Generator - MD5, SHA-1, SHA-256, SHA-512, SHA-3 Online',
    description: 'Generate cryptographic hashes (MD5, SHA-1, SHA-256, SHA-512, SHA-3, BLAKE) from any text or file. Features multiple algorithms, file hashing, HMAC support, and copy functionality. 100% client-side for maximum security. Free hash generator for developers.',
    path: '/hash-generator',
    keywords: [
      'hash generator',
      'md5 generator',
      'sha256 generator',
      'sha512 generator',
      'sha1 hash',
      'cryptographic hash',
      'file hash generator',
      'text hash online',
      'checksum generator',
      'md5 checksum',
      'sha checksum',
      'hmac generator',
      'hash calculator',
      'message digest',
      'secure hash algorithm',
      'blake hash',
      'password hash',
      'data integrity',
      'file verification',
      'best hash generator',
    ],
    ogTitle: 'Hash Generator - MD5, SHA-256, SHA-512 Online',
    ogDescription: 'Generate MD5, SHA-1, SHA-256, SHA-512 hashes instantly. File support, HMAC, 100% client-side. Free!',
    category: 'Security Tools',
    priority: 0.8,
    changeFrequency: 'monthly',
    features: ['Multiple algorithms', 'File hashing', 'HMAC support', 'Copy to clipboard', 'Lower/Upper case'],
    useCases: ['Password hashing', 'File verification', 'Data integrity', 'API signatures'],
    relatedTools: ['base64', 'jwt-decoder', 'uuid-generator'],
  },
  
  'jwt-decoder': {
    title: 'JWT Decoder - Decode & Inspect JSON Web Tokens Online',
    description: 'Decode and inspect JWT tokens instantly to view header, payload, and signature. Features token validation, expiration checking, Base64 decoding, and signature verification guidance. Supports RS256, HS256, and other algorithms. 100% client-side, secure, and free.',
    path: '/jwt-decoder',
    keywords: [
      'jwt decoder',
      'jwt parser',
      'decode jwt online',
      'json web token decoder',
      'jwt inspector',
      'jwt token viewer',
      'jwt debugger',
      'jwt validator',
      'jwt signature checker',
      'base64 jwt decoder',
      'jwt payload viewer',
      'jwt header decoder',
      'jwt expiration check',
      'access token decoder',
      'id token decoder',
      'jwt token breakdown',
      'jwt online tool',
      'jwt analyzer',
      'jwt verification tool',
      'best jwt decoder',
    ],
    ogTitle: 'JWT Decoder - Decode JSON Web Tokens Online',
    ogDescription: 'Decode JWT tokens instantly. View header, payload & signature. Token validation, 100% client-side. Free!',
    category: 'Developer Tools',
    priority: 0.85,
    changeFrequency: 'monthly',
    features: ['Header decode', 'Payload decode', 'Signature display', 'Expiration check', 'Algorithm info'],
    useCases: ['API debugging', 'Token inspection', 'Security analysis', 'OAuth debugging'],
    relatedTools: ['base64', 'hash-generator', 'uuid-generator'],
  },
  
  'csv-to-json': {
    title: 'CSV to JSON Converter - Convert CSV to JSON Online Free',
    description: 'Convert CSV files to JSON format instantly with automatic header detection, data type inference, and nested object support. Features delimiter detection, encoding options, and bulk conversion. Handles large CSV files efficiently. 100% client-side, free, and privacy-focused.',
    path: '/csv-to-json',
    keywords: [
      'csv to json',
      'csv converter',
      'csv parser',
      'convert csv to json',
      'csv to json online',
      'csv file converter',
      'excel to json',
      'spreadsheet to json',
      'csv json transformer',
      'csv data converter',
      'delimiter detection',
      'csv header mapping',
      'bulk csv converter',
      'csv to json api',
      'tabular data converter',
      'csv json online tool',
      'comma separated values',
      'tsv to json',
      'csv to object',
      'best csv converter',
    ],
    ogTitle: 'CSV to JSON Converter - Convert CSV to JSON Online',
    ogDescription: 'Convert CSV to JSON instantly. Auto header detection, type inference, bulk support. Free & client-side!',
    category: 'Data Conversion',
    priority: 0.85,
    changeFrequency: 'monthly',
    features: ['Header detection', 'Type inference', 'Delimiter options', 'Nested objects', 'Bulk support'],
    useCases: ['Data migration', 'API data prep', 'Database import', 'Report generation'],
    relatedTools: ['xml-to-json', 'yaml-to-json', 'json-formatter', 'json-to-typescript'],
  },
  
  'xml-to-json': {
    title: 'XML to JSON Converter - Bidirectional XML JSON Converter',
    description: 'Convert between XML and JSON formats bidirectionally with intelligent attribute handling, namespace support, and CDATA preservation. Features syntax highlighting, error detection, and pretty printing. Perfect for API integration and legacy system migration. Free online converter.',
    path: '/xml-to-json',
    keywords: [
      'xml to json',
      'json to xml',
      'xml converter',
      'xml parser',
      'convert xml to json',
      'xml json transformer',
      'xml data converter',
      'xml attribute handler',
      'xml namespace converter',
      'bidirectional xml json',
      'xml formatter',
      'xml validator',
      'xml online tool',
      'xml to object',
      'soap to json',
      'rest xml converter',
      'xml api converter',
      'xml schema converter',
      'legacy xml migration',
      'best xml converter',
    ],
    ogTitle: 'XML to JSON Converter - Bidirectional Converter',
    ogDescription: 'Convert XML to JSON bidirectionally. Attribute handling, namespace support, CDATA preservation. Free!',
    category: 'Data Conversion',
    priority: 0.8,
    changeFrequency: 'monthly',
    features: ['Bidirectional', 'Attribute handling', 'Namespace support', 'CDATA preservation', 'Syntax highlight'],
    useCases: ['API integration', 'Legacy migration', 'Data transformation', 'SOAP services'],
    relatedTools: ['csv-to-json', 'yaml-to-json', 'json-formatter', 'json-to-typescript'],
  },
  
  'yaml-to-json': {
    title: 'YAML to JSON Converter - Convert YAML to JSON Online',
    description: 'Convert between YAML and JSON formats with anchor/alias resolution, multi-document support, and comment preservation. Features syntax highlighting, error detection, and formatting options. Perfect for Docker Compose, Kubernetes, and configuration files. Free online YAML converter.',
    path: '/yaml-to-json',
    keywords: [
      'yaml to json',
      'json to yaml',
      'yaml converter',
      'yaml parser',
      'convert yaml to json',
      'yaml json transformer',
      'yaml online tool',
      'yaml formatter',
      'yaml validator',
      'docker compose converter',
      'kubernetes yaml json',
      'yaml config converter',
      'yaml anchor alias',
      'multi document yaml',
      'yaml syntax checker',
      'yaml indentation',
      'yaml to object',
      'yaml vs json',
      'yaml configuration',
      'best yaml converter',
    ],
    ogTitle: 'YAML to JSON Converter - Bidirectional Converter',
    ogDescription: 'Convert YAML to JSON bidirectionally. Anchor/alias support, multi-document, Docker/K8s ready. Free!',
    category: 'Data Conversion',
    priority: 0.8,
    changeFrequency: 'monthly',
    features: ['Bidirectional', 'Anchor/alias support', 'Multi-document', 'Comment handling', 'Syntax highlight'],
    useCases: ['Docker Compose', 'Kubernetes', 'CI/CD configs', 'CloudFormation'],
    relatedTools: ['csv-to-json', 'xml-to-json', 'json-formatter', 'json-to-typescript'],
  },
  
  'image-compressor': {
    title: 'Image Compressor - Compress Images Online Free (JPG, PNG, WebP)',
    description: 'Compress images with adjustable quality while maintaining visual clarity. Supports JPG, PNG, WebP formats with real-time size reduction preview. Features batch processing, format conversion, and EXIF preservation. 100% client-side processing - your images never leave your browser. Free tool.',
    path: '/image-compressor',
    keywords: [
      'image compressor',
      'compress image online',
      'reduce image size',
      'image optimizer',
      'compress jpg',
      'compress png',
      'webp converter',
      'image size reducer',
      'photo compressor',
      'bulk image compression',
      'lossless compression',
      'lossy compression',
      'image quality optimizer',
      'web image optimizer',
      'image file size reducer',
      'compress images for web',
      'email image compressor',
      'social media image optimizer',
      'website image optimizer',
      'best image compressor',
    ],
    ogTitle: 'Image Compressor - Compress Images Online Free',
    ogDescription: 'Compress JPG, PNG, WebP images instantly. Adjustable quality, size reduction preview. Free & secure!',
    category: 'Media Tools',
    priority: 0.8,
    changeFrequency: 'monthly',
    features: ['Quality adjustment', 'Multiple formats', 'Size preview', 'Batch processing', 'EXIF preservation'],
    useCases: ['Web optimization', 'Email attachments', 'Social media', 'Storage saving'],
    relatedTools: ['color-converter', 'qr-generator', 'ascii-art'],
  },
  
  'ascii-art': {
    title: 'ASCII Art Generator - Text to ASCII Art Online Free',
    description: 'Convert text to stunning ASCII art with multiple font styles including banner, block, and decorative fonts. Features instant preview, copy-to-clipboard, and supports special characters. Perfect for terminal headers, code comments, and creative projects. Free ASCII art generator.',
    path: '/ascii-art',
    keywords: [
      'ascii art generator',
      'text to ascii',
      'ascii art maker',
      'ascii text generator',
      'ascii banner',
      'ascii font generator',
      'figlet generator',
      'ascii logo maker',
      'terminal ascii art',
      'ascii code art',
      'ascii decoration',
      'text banner generator',
      'ascii word art',
      'ascii heading',
      'code comment art',
      'ascii signature',
      'ascii art styles',
      'big text generator',
      'monospace art',
      'best ascii generator',
    ],
    ogTitle: 'ASCII Art Generator - Text to ASCII Art Online',
    ogDescription: 'Convert text to ASCII art instantly. Multiple styles, instant preview, copy-ready. Free online tool!',
    category: 'Creative Tools',
    priority: 0.75,
    changeFrequency: 'monthly',
    features: ['Multiple fonts', 'Instant preview', 'Copy to clipboard', 'Special characters', 'Large text'],
    useCases: ['Terminal headers', 'Code comments', 'Creative projects', 'Documentation'],
    relatedTools: ['color-converter', 'qr-generator', 'image-compressor'],
  },
  
  'url-encoder': {
    title: 'URL Encoder & Decoder - Encode URLs Online Free',
    description: 'Encode and decode URLs, query strings, and URI components instantly. Features automatic detection, full/partial encoding options, and special character handling. Perfect for API testing, web development, and form data preparation. Free online URL encoder/decoder.',
    path: '/url-encoder',
    keywords: [
      'url encoder',
      'url decoder',
      'encode url online',
      'decode url online',
      'url escape',
      'url encode decode',
      'percent encoding',
      'uri encoder',
      'query string encoder',
      'url component encoder',
      'special character encoder',
      'url safe encoding',
      'rfc 3986 encoder',
      'javascript encodeuri',
      'encodeuricomponent',
      'url parameter encoder',
      'form data encoder',
      'base64 url encoding',
      'url parsing tool',
      'best url encoder',
    ],
    ogTitle: 'URL Encoder & Decoder - Encode URLs Online',
    ogDescription: 'Encode & decode URLs instantly. Query strings, special characters, API testing ready. Free tool!',
    category: 'Encoding Tools',
    priority: 0.8,
    changeFrequency: 'monthly',
    features: ['Auto detection', 'Full/partial encoding', 'Query string support', 'Copy to clipboard', 'History'],
    useCases: ['API testing', 'Web development', 'Form data', 'URL cleaning'],
    relatedTools: ['base64', 'regex-tester', 'qr-generator'],
  },
  
  'timestamp-converter': {
    title: 'Timestamp Converter - Unix Timestamp to Date & Time Online',
    description: 'Convert Unix timestamps to human-readable dates and vice versa. Supports multiple formats, timezone conversion, and relative time calculations. Features instant conversion, copy functionality, and timezone detection. Free online timestamp converter for developers.',
    path: '/timestamp-converter',
    keywords: [
      'timestamp converter',
      'unix timestamp',
      'epoch converter',
      'timestamp to date',
      'unix time converter',
      'epoch time',
      'convert timestamp',
      'milliseconds to date',
      'seconds to date',
      'iso 8601 converter',
      'utc timestamp',
      'timezone converter',
      'relative time',
      'date to timestamp',
      'unix epoch',
      'javascript timestamp',
      'mysql timestamp',
      'postgres timestamp',
      'timestamp formatter',
      'best timestamp converter',
    ],
    ogTitle: 'Timestamp Converter - Unix Timestamp to Date Online',
    ogDescription: 'Convert Unix timestamps to dates instantly. Multiple formats, timezone support, relative time. Free!',
    category: 'Utility Tools',
    priority: 0.8,
    changeFrequency: 'monthly',
    features: ['Multiple formats', 'Timezone support', 'Relative time', 'Bidirectional', 'Copy to clipboard'],
    useCases: ['Log analysis', 'Database work', 'API debugging', 'Server timestamps'],
    relatedTools: ['uuid-generator', 'hash-generator', 'jwt-decoder'],
  },
  
  'json-diff': {
    title: 'JSON Diff - Compare JSON Files & Objects Online Free',
    description: 'Compare two JSON objects side-by-side with visual highlighting of differences, additions, deletions, and modifications. Features nested comparison, array diffing, and merge suggestions. Perfect for API response comparison, config file diffing, and debugging. Free online JSON diff tool.',
    path: '/json-diff',
    keywords: [
      'json diff',
      'json compare',
      'compare json',
      'json difference',
      'json comparison tool',
      'diff json files',
      'json object compare',
      'json patch generator',
      'json merge tool',
      'api response compare',
      'config file diff',
      'json syntax diff',
      'nested json compare',
      'array diff json',
      'json visual diff',
      'json changelog',
      'json version compare',
      'deep json compare',
      'json delta viewer',
      'best json diff tool',
    ],
    ogTitle: 'JSON Diff - Compare JSON Objects Online',
    ogDescription: 'Compare JSON files side-by-side. Visual diff, nested support, merge suggestions. Free online tool!',
    category: 'JSON Tools',
    priority: 0.8,
    changeFrequency: 'monthly',
    features: ['Side-by-side view', 'Visual highlighting', 'Nested comparison', 'Array diffing', 'Merge suggestions'],
    useCases: ['API debugging', 'Config comparison', 'Version tracking', 'Data validation'],
    relatedTools: ['json-formatter', 'json-to-typescript', 'json-to-zod', 'validator'],
  },
  
  'validator': {
    title: 'Zod Validator - Validate JSON Data with Zod Schemas Online',
    description: 'Validate JSON data against Zod schemas with detailed error messages, type checking, and transformation support. Features real-time validation, custom error messages, and schema recommendations. Perfect for form validation, API testing, and data integrity checks. Free online Zod validator.',
    path: '/validator',
    keywords: [
      'zod validator',
      'schema validator',
      'json validator',
      'data validation',
      'zod validation online',
      'zod schema tester',
      'runtime validation',
      'typescript validation',
      'form validation tool',
      'api data validator',
      'json schema validator',
      'type checking online',
      'zod error messages',
      'zod transformation',
      'zod refinement',
      'zod custom validation',
      'zod typescript',
      'zod playground',
      'zod test tool',
      'best zod validator',
    ],
    ogTitle: 'Zod Validator - Validate Data with Zod Schemas',
    ogDescription: 'Validate JSON with Zod schemas instantly. Detailed errors, type checking, transformations. Free tool!',
    category: 'Validation Tools',
    priority: 0.8,
    changeFrequency: 'monthly',
    features: ['Real-time validation', 'Detailed errors', 'Type checking', 'Transformation support', 'Schema suggestions'],
    useCases: ['Form validation', 'API testing', 'Data integrity', 'Type checking'],
    relatedTools: ['json-to-zod', 'json-to-typescript', 'json-diff', 'json-formatter'],
  },
  
  'json-to-json-schema': {
    title: 'JSON to JSON Schema Generator - Create JSON Schemas Online',
    description: 'Generate JSON Schema (Draft 7, 2019-09, 2020-12) from JSON data automatically. Features type inference, validation rules, required field detection, and schema customization. Perfect for API documentation, data validation, and OpenAPI specs. Free JSON Schema generator.',
    path: '/json-to-json-schema',
    keywords: [
      'json to json schema',
      'json schema generator',
      'generate json schema',
      'json schema maker',
      'json schema creator',
      'json schema draft 7',
      'json schema 2019',
      'json schema 2020',
      'json validation schema',
      'openapi schema',
      'json schema inference',
      'json schema builder',
      'json schema online',
      'json schema validator',
      'json schema properties',
      'json schema required',
      'json schema types',
      'api schema generator',
      'json schema documentation',
      'best json schema generator',
    ],
    ogTitle: 'JSON to JSON Schema Generator - Create Schemas',
    ogDescription: 'Generate JSON Schema from JSON data instantly. Type inference, validation rules, OpenAPI ready. Free!',
    category: 'JSON Tools',
    priority: 0.75,
    changeFrequency: 'monthly',
    features: ['Type inference', 'Validation rules', 'Required fields', 'Multi-draft support', 'Schema customization'],
    useCases: ['API documentation', 'Data validation', 'OpenAPI specs', 'Schema design'],
    relatedTools: ['json-schema-to-typescript', 'json-to-typescript', 'json-to-zod', 'validator'],
  },
  
  'json-schema-to-typescript': {
    title: 'JSON Schema to TypeScript - Convert Schemas to TypeScript Types',
    description: 'Convert JSON Schema to TypeScript interfaces and types with full Draft 7/2019-09/2020-12 support. Features complex type handling, enum generation, and reference resolution. Perfect for API clients, type generation, and maintaining type safety. Free online converter.',
    path: '/json-schema-to-typescript',
    keywords: [
      'json schema to typescript',
      'schema to typescript',
      'json schema converter',
      'typescript from schema',
      'json schema types',
      'generate typescript from schema',
      'json schema interface',
      'json schema type generator',
      'openapi to typescript',
      'swagger to typescript',
      'json schema definitions',
      'json schema references',
      'json schema enums',
      'json schema union types',
      'json schema anyOf',
      'json schema oneOf',
      'json schema allOf',
      'complex schema converter',
      'json schema compiler',
      'best schema converter',
    ],
    ogTitle: 'JSON Schema to TypeScript - Convert Schemas to Types',
    ogDescription: 'Convert JSON Schema to TypeScript instantly. Full Draft support, complex types, enum generation. Free!',
    category: 'JSON Tools',
    priority: 0.75,
    changeFrequency: 'monthly',
    features: ['Full Draft support', 'Complex types', 'Enum generation', 'Reference resolution', 'Interface naming'],
    useCases: ['API clients', 'Type generation', 'Schema migration', 'Type safety'],
    relatedTools: ['json-to-json-schema', 'json-to-typescript', 'typescript-to-zod', 'zod-to-typescript'],
  },
  
  'typescript-to-zod': {
    title: 'TypeScript to Zod - Convert TS Types to Zod Schemas Online',
    description: 'Convert TypeScript types, interfaces, and enums to Zod validation schemas automatically. Features generic support, union types, and complex type handling. Perfect for adding runtime validation to existing TypeScript projects. Free online TypeScript to Zod converter.',
    path: '/typescript-to-zod',
    keywords: [
      'typescript to zod',
      'ts to zod',
      'convert typescript to zod',
      'zod from typescript',
      'interface to zod',
      'typescript zod converter',
      'generate zod from ts',
      'type to zod schema',
      'typescript runtime validation',
      'zod schema from interface',
      'typescript enum to zod',
      'typescript union to zod',
      'generic types zod',
      'typescript zod generator',
      'zod inference from ts',
      'ts types to validators',
      'typescript validation schema',
      'zod schema builder',
      'type safe validation',
      'best ts to zod converter',
    ],
    ogTitle: 'TypeScript to Zod - Convert TS Types to Zod Schemas',
    ogDescription: 'Convert TypeScript to Zod schemas instantly. Generic support, unions, complex types. Free online tool!',
    category: 'Validation Tools',
    priority: 0.75,
    changeFrequency: 'monthly',
    features: ['Generic support', 'Union types', 'Enum conversion', 'Complex types', 'Interface support'],
    useCases: ['Runtime validation', 'Type migration', 'Schema creation', 'Type safety'],
    relatedTools: ['zod-to-typescript', 'json-to-zod', 'json-to-typescript', 'validator'],
  },
  
  'zod-to-typescript': {
    title: 'Zod to TypeScript - Extract Types from Zod Schemas Online',
    description: 'Extract TypeScript types, interfaces, and enums from Zod validation schemas automatically. Features type inference, generic preservation, and complex schema support. Perfect for documentation generation and maintaining type consistency. Free online Zod to TypeScript converter.',
    path: '/zod-to-typescript',
    keywords: [
      'zod to typescript',
      'zod to ts',
      'extract zod types',
      'typescript from zod',
      'zod schema to interface',
      'zod type inference',
      'zod to type',
      'generate typescript from zod',
      'zod typescript export',
      'zod to type alias',
      'zod interface generator',
      'zod types extraction',
      'zod to ts types',
      'zod schema types',
      'zod type definitions',
      'zod documentation',
      'zod type generator',
      'zod inference helper',
      'zod schema converter',
      'best zod to ts converter',
    ],
    ogTitle: 'Zod to TypeScript - Extract Types from Zod Schemas',
    ogDescription: 'Extract TypeScript types from Zod schemas instantly. Type inference, generics, complex schemas. Free tool!',
    category: 'Validation Tools',
    priority: 0.75,
    changeFrequency: 'monthly',
    features: ['Type inference', 'Generic preservation', 'Enum extraction', 'Complex schemas', 'Documentation'],
    useCases: ['Type extraction', 'Documentation', 'Type consistency', 'Schema sharing'],
    relatedTools: ['typescript-to-zod', 'json-to-zod', 'json-to-typescript', 'validator'],
  },
};

export const toolsMetadata: Record<string, Metadata> = Object.fromEntries(
  Object.entries(toolsData).map(([key, data]) => [
    key,
    generatePageMetadata(data),
  ])
);

export function getToolMetadata(toolId: string): Metadata {
  return toolsMetadata[toolId] || toolsMetadata['json-to-typescript'];
}

export function getToolInfo(toolId: string): ToolInfo | undefined {
  return toolsData[toolId];
}

export function getAllTools(): ToolInfo[] {
  return Object.values(toolsData);
}

export function getRelatedTools(toolId: string): ToolInfo[] {
  const tool = toolsData[toolId];
  if (!tool) return [];
  
  return tool.relatedTools
    .map(id => toolsData[id])
    .filter(Boolean) as ToolInfo[];
}

export function getToolsByCategory(category: string): ToolInfo[] {
  return Object.values(toolsData).filter(tool => tool.category === category);
}

export function getAllCategories(): string[] {
  const categories = new Set(Object.values(toolsData).map(tool => tool.category));
  return Array.from(categories).sort();
}
